name: Build and deploy ASP.NET Core app to Azure Web App - otherTest

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PROJECT_PATH: PTR.Mongo.WebApp/PTR.Mongo.WebApp.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "$PROJECT_PATH"

      - name: Build
        run: dotnet build "$PROJECT_PATH" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "$PROJECT_PATH" -c Release -o ${{ env.DOTNET_ROOT }}/myapp --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6241E8BD763C4AA0BD6F2276E2C82931 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DE396048CD9845798DE9AB7763D148E3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_417D016D2C96463BA2D2F838684BFF07 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: otherTest
          slot-name: Production
          package: .